### ISSUE TITLE
Error attempting to update existing ESPHome bluetooth proxies

### ISSUE THREAD

**Issue by MakerDockio** [esphome/bluetooth-proxies#54]
I have just attempted to update my two existing ESPHome esp32 bluetooth proxies via the ESPHome Dashboard in Home Assistant to the latest firmware. When attempting I get the following error in the log.

![Screenshot 2022-12-08 at 16 16 15](https://user-images.githubusercontent.com/64750327/206503154-b827525f-00ae-4625-90fd-d8437e3eeb84.png)

The proxies are running on thr Generic ESP32 WROOM modules, with Home Assistant (2022-12) / ESPHome (2022.11.5 ) running on Raspberry Pi 4.

Any pointers would be appreciated.

**Comment by MakerDockio** [comment]
Roger that 👍! Cheers Paulus

**Comment by bbostock** [comment]
I have also been unable to compile the new update for bluetooth proxies following installation of 2022.12.5 & updating ESPHome. 

After reading this thread I tried the beta, but sadly it fails with the same error: 

`Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.30.2") 
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc -- broken
-- Configuring incomplete, errors occurred!
See also "/data/atom-bluetooth-proxy-a6d1e8/.pioenvs/atom-bluetooth-proxy-a6d1e8/CMakeFiles/CMakeOutput.log".
See also "/data/atom-bluetooth-proxy-a6d1e8/.pioenvs/atom-bluetooth-proxy-a6d1e8/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/tool-cmake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/atom-bluetooth-proxy-a6d1e8/.pioenvs/atom-bluetooth-proxy-a6d1e8/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/data/cache/platformio/packages/tool-ninja/ninja cmTC_8e143 && [1/2] Building C object CMakeFiles/cmTC_8e143.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_8e143.dir/testCCompiler.c.obj 
    /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc   -mlongcalls -Wno-frame-address -o CMakeFiles/cmTC_8e143.dir/testCCompiler.c.obj   -c testCCompiler.c
    /bin/sh: 1: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc: not found
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:296 (__project)
  CMakeLists.txt:3 (project)



========================= [FAILED] Took 252.15 seconds =========================`

Any help greatly appreciated.

**Comment by nagyrobi** [comment]
Try a Clean Build Files from the 3-dot menu!

**Comment by bbostock** [comment]
That was the first thing I did. But sadly made no difference.

**Comment by stefanthoss** [comment]
I faced similar build issues on my WT32-ETH01 and they were resolved with the ESPHome [release 2022.12.0](https://esphome.io/changelog/2022.12.0.html) from today.

**Comment by nagyrobi** [comment]
**xtensa-esp32-elf-g++ not found**
With the recent update of ESPHome, it seems that if you are using a 32-bit OS on a 64-bit RPi4 the toolchain is incorrectly downloaded and you get an error during compilation: `xtensa-esp32-elf-g++ not found`.
We are looking into a fix, but the best recommendation right now is to reinstall your OS to actually use a 64-bit based OS as intended. 
You can rollback ESPHome to before 2022.12.0 but this is not a permanent solution.

**Comment by bbostock** [comment]
Ok, thank you for the diagnosis. I'll consider my options before proceeding.

It's very cold here at the moment and I don't think my wife would appreciate me experimenting when the current setup runs our heating system. 
🙏

**Comment by Gferretta** [comment]
Hi
I have exactly same error running ESPHOME in a RPi3+ with an SD
No can update existing BT Proxies ESP32 (Generic) over wifi or cable.
No compile at all.

ESPHome 2022.12.3
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by balloob** [comment]
The original issue here has been resolved because the new ESPHome has been released.

**Comment by bbostock** [comment]
Do I assume that it will be distributed with the January 23 HA release, or is there a way to install ESPHome sooner? (I tried re-installing the ESPHome beta, but it fails too).
Thank you
Bill

**Comment by bbostock** [comment]
Despite this apparently being resolved and I'm running the latest HA / ESPHome, it still fails with the same error. 
Please provide some further guidance if I need to do something else.
Thank you
Bill
